// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDclRYRd8_mS6VlMRl4UlTf6r9otCGScjk',
    appId: '1:468639700183:web:1c0aa70721ef0d60068c92',
    messagingSenderId: '468639700183',
    projectId: 'todolist-b52-24',
    authDomain: 'todolist-b52-24.firebaseapp.com',
    storageBucket: 'todolist-b52-24.firebasestorage.app',
    measurementId: 'G-S0G1BBTPC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7-yY3wUMtzirETpj1CH-G2CPnyuqVH0',
    appId: '1:468639700183:android:f316c0aaa24421b0068c92',
    messagingSenderId: '468639700183',
    projectId: 'todolist-b52-24',
    storageBucket: 'todolist-b52-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdeYa5NOVuynI76Ch_UMJogmQDxsZcS5g',
    appId: '1:468639700183:ios:d45943f5d8e318af068c92',
    messagingSenderId: '468639700183',
    projectId: 'todolist-b52-24',
    storageBucket: 'todolist-b52-24.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );
}
